---
title: "News"
---
&nbsp;

- **October 1** Kerstin starting as PhD student in the lab

### 2019 

- **November 12** Tom submitted his thesis. Congrats
- **September 30** Sophie successfully defended her thesis. Congrats
- **September 15 -25** Markus participates in a visit to Beijing, Nanjing and Shanghai presenting work from the lab  
- **September 15** Jose presenting a poster at the [meeting of the German Botanical Society](https://www.botanikertagung2019.de/)  
- **June 19** Markus Presenting at CEPLAS meeting in Duesseldorf  
- **April 15** Welcome Jose Dias as PhD student in the lab
- **March 1** We are officially open for business   
- **February 13** New preprint online. Read it [here](https://www.biorxiv.org/content/10.1101/547943v1)  
- **December 20** Open PhD student position in the lab [read more](files/phd_offer2018.pdf)  
- **November 27** lab website comes to life  



<!--<a class="twitter-timeline" href="https://twitter.com/MGStetter?ref_src=twsrc%5Etfw">Tweets by MGStetter</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

-->

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-96594188-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-96594188-4');
</script>
