---
title: "What we read"
---
&nbsp;

C.R.O.P is our weekly journal club for anyone interested in evolution. 
We meet on Tuesday at 4.15 pm at [Theatercafe Filmdose](https://goo.gl/maps/mamsnSV5ZqThF4YY8) for an open discussion about the weekly paper in a relaxed atmosphere. 

**Until further notice we will meet in the seminar room on the 3rd floor of the CoMB**

Anybody is welcome to join us.
The idea is that everyone reads the paper before and we dive directly in without formal presentation of the paper. 
If you would like to suggest a paper please email [Markus](mailto:m.stetter@uni-koeln.de).


### April
#### Tuesday April 29
[Gompert et al, 2025](https://www.science.org/doi/abs/10.1126/science.adp3745) 
Adaptation repeatedly uses complex structural genomic variation

#### Tuesday April 22
Easter break

#### Tuesday April 15
[Liu et al, 2025](https://www.nature.com/articles/s41588-025-02122-4) 
Origin and de novo domestication of sweet orange


#### Tuesday April 8
[Zhang et al, 2025](https://www.nature.com/articles/s41477-025-01905-1) 
Transposon proliferation drives genome architecture and regulatory evolution in wild and domesticated peppers

#### Tuesday April 1
[Sedeek et al, preprint](https://www.biorxiv.org/content/10.1101/2025.03.03.641344v1) 
Nutritional quality and genetic differences of five amaranth cultivars revealed by metabolome profiling and whole-genome sequencing

### March

#### Tuesday March 25
[Zhang et al, 2025](https://www.nature.com/articles/s41559-025-02653-3) 
Genetic basis of camouflage in an alpine plant and its long-term co-evolution with an insect herbivore

### February

#### Tuesday February 25
[Castellano et al, preprint](https://www.biorxiv.org/content/10.1101/2022.08.24.505198v4) 
Detection of Domestication Signals through the Analysis of the Full Distribution of Fitness Effects

#### Tuesday February 18
[Shaw et al, 2025](https://www.nature.com/articles/s41586-024-08458-x) 
Global meta-analysis shows action is needed to halt genetic diversity loss

#### Tuesday February 11
[Chevin and Bridle, 2025](https://royalsocietypublishing.org/doi/10.1098/rstb.2023.0322) 
Impacts of limits to adaptation on population and community persistence in a changing environment

#### Tuesday February 4
[Cheng et al, 2025](https://www.nature.com/articles/s41586-024-08476-9) 
Leveraging a phased pangenome for haplotype design of hybrid potato


### January

#### Tuesday January 28
[Groh et al, 2024](https://www.science.org/doi/10.1126/science.ado5578) 
Ancient structural variants control sex-specific flowering time morphs in walnuts and hickories

#### Tuesday January 21
TRR 341 Seminar

#### Tuesday January 14
[Ramos-Madrigal et al, 2024](https://www.cell.com/cell/abstract/S0092-8674(24)01277-7) 
The genomic origin of early maize in eastern North America

## 2024

### December

#### Tuesday December 3
[Burgarella et al, 2024](https://academic.oup.com/evlett/advance-article/doi/10.1093/evlett/qrae039/7731525?login=false) 
Mating systems and recombination landscape strongly shape genetic diversity and selection in wheat relatives

### November

#### Tuesday November 26
[Bertolini et al., 2023](https://www.biorxiv.org/content/10.1101/2023.08.19.553731) 
Regulatory variation controlling architectural pleiotropy in maize

#### Tuesday November 19
[Guillotin et al., 2023](https://www.nature.com/articles/s41586-023-06053-0) 
A pan-grass transcriptome reveals patterns of cellular divergence in crops


#### Tuesday November 5
[Ni et al, 2024](https://www.science.org/doi/10.1126/science.ado5331) 
Human-driven evolution of color in a stonefly mimic


### October

#### Tuesday October 29
[Schuh and Morris, preprint](https://www.biorxiv.org/content/10.1101/2024.10.03.615829v1.full) 
Loss of pleiotropic regulatory functions in Tannin1, the sorghum ortholog of Arabidopsis master regulator TTG1

#### Tuesday October 22
[McKenzie et al, preprint](https://www.biorxiv.org/content/10.1101/2024.09.25.614826v1.full) 
A massive community-science flower color dataset reveals convergent evolution of delayed flowering phenology in North American red-flowering plants

#### Tuesday October 15
TRR 341 seminar

#### Tuesday October 8
[Huang et al, preprint](https://www.biorxiv.org/content/10.1101/2024.09.17.613564v1.full) 
Varying recombination landscapes between individuals are driven by polymorphic transposable elements


#### Tuesday October 1
[Li, preprint](https://www.biorxiv.org/content/10.1101/2024.09.19.613351v1) 
The utility of environmental data from traditional varieties for climate-adaptive maize breeding


### September

#### Tuesday September 24
[Short and Streisfeld, preprint](https://www.biorxiv.org/content/10.1101/2024.08.26.609732v1.full) 
The genomic outcomes of hybridization vary over time within a monkeyflower radiation

#### Tuesday September 17
[Long, preprint](https://www.biorxiv.org/content/10.1101/2024.02.14.580345v1.full) 
Muller’s Ratchet in Action: The Erosion of Sexual Reproduction Genes in Domesticated Cassava (Manihot esculenta)


#### Tuesday September 10
[Booker, 2024](https://academic.oup.com/evlett/advance-article/doi/10.1093/evlett/qrae033/7735308) 
The structure of the environment influences the patterns and genetics of local adaptation

#### Tuesday September 3
[Fiscus, et al, preprint](https://www.biorxiv.org/content/10.1101/2024.08.22.609253v1) 
Climate, population size, and dispersal influences mutational load across the landscape in Vitis arizonica

### August
Summer break

### July

#### Tuesday July 30
[Landis et al, 2024](https://www.science.org/doi/10.1126/science.adl0038) 
Natural selection drives emergent genetic homogeneity in a century-scale experiment with barley

#### Tuesday July 23
[Arca et al, 2023](https://onlinelibrary.wiley.com/doi/full/10.1111/pbi.14022) 
Genotyping of DNA pools identifies untapped landraces and genomic regions to develop next-generation varieties

#### Tuesday July 16
[Cao et al, 2024](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-024-03310-x) 
DNA methylation variations underlie lettuce domestication and divergence

#### Tuesday July 9
[Andrade et al, 2024](https://www.nature.com/articles/s41559-024-02443-3) 
Selection against domestication alleles in introduced rabbit populations


#### Tuesday July 2
[Ament-Velásquez et al, 2022](https://academic.oup.com/mbe/article/39/11/msac242/6806091) 
The Dynamics of Adaptation to Stress from Standing Genetic Variation and de novo Mutations

### June

#### Tuesday June 25
[Zhang et al, 2024](https://www.science.org/doi/10.1126/science.ade4487) 
Rice’s trajectory from wild to domesticated in East Asia


#### Tuesday June 18
[Smith and Hahn, preprint](https://www.biorxiv.org/content/10.1101/2023.10.27.564394v3) 
Selection leads to false inferences of introgression using popular methods


### May

#### Tuesday May 28
[Garner et al, preprint](https://www.biorxiv.org/content/10.1101/2023.04.19.537550v1.full)
A cis-regulatory point mutation at a R2R3-Myb transcription factor contributes to speciation by reinforcement in Phlox drummondii

#### Tuesday May 21
[Schraiber et al, preprint](https://www.biorxiv.org/content/10.1101/2024.02.10.579721v2.full)
Unifying approaches from statistical genetics and phylogenetics for mapping phenotypes in structured populations

#### Tuesday May 14
[Sun et al, 2024](https://nph.onlinelibrary.wiley.com/doi/abs/10.1111/nph.19738)
A WOX homolog disrupted by a transposon led to the loss of spines and contributed to the domestication of lettuce

#### Tuesday May 7
[Lian et al, 2024](https://www.nature.com/articles/s41588-024-01715-9)
A pan-genome of 69 Arabidopsis thaliana accessions reveals a conserved genome structure throughout the global species range

### April

#### Tuesday April 30
No CROP

#### Tuesday April 23
[Sianta et al, 2024](https://www.pnas.org/doi/10.1073/pnas.2316008121)
The extent of introgression between incipient Clarkia species is determined by temporal environmental variation and mating system

#### Tuesday April 16
TRR 341 seminar

#### Tuesday April 9
[Nocchi et al, preprint](https://www.biorxiv.org/content/10.1101/2024.04.02.587814v1)
Repeated global adaptation across plant species


#### Tuesday April 2
Easter break

### March


#### Tuesday March 26
Easter break


#### Tuesday March 19
[ He et al, 2024](https://www.nature.com/articles/s41588-024-01655-4)
Large-scale gene expression alterations introduced by structural variation drive morphotype diversification in Brassica oleracea

#### Tuesday March 12
[ He et al, 2024](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-024-03203-z)
Genomic insight into the origin, domestication, dispersal, diversification and human selection of Tartary buckwheat

#### Tuesday March 5
[ Walter et al, 2024](https://academic.oup.com/evlett/advance-article/doi/10.1093/evlett/qrad065/7577653)
Environmental effects on genetic variance are likely to constrain adaptation in novel environments 

### Feburary

#### Tuesday February 20
[Pope et al, 2023](https://www.pnas.org/doi/full/10.1073/pnas.2208116120)
The expansion of agriculture has shaped the recent evolutionary history of a specialized squash pollinator

#### Thursday February 1
[Kreiner, et al., 2023](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1010865)
Quantifying the role of genome size and repeat content in adaptive variation and the architecture of flowering time in Amaranthus tuberculatus

### January

#### Thursday January 25
[Langmüller, et al., 2023](https://academic.oup.com/nar/article/51/17/9203/7240371?login=true)
The genomic distribution of transposable elements is driven by spatially variable purifying selection 


## 2023


### December

#### Thursday December 7
[Ruffley, et al., preprint](https://www.biorxiv.org/content/10.1101/2023.10.16.562583v1)
Conflicts in natural selection constrain adaptation to climate change in Arabidopsis thaliana

### November
#### Thursday November 30
[O’Brien, et al., preprint](https://www.biorxiv.org/content/10.1101/2023.10.26.564303v2)
The distribution of fitness effects during adaptive walks using a simple genetic network


#### Thursday November 23
[Desbiez-Piat, et al., 2023](https://academic.oup.com/genetics/advance-article/doi/10.1093/genetics/iyad186/7310833)
Pervasive G × E interactions shape adaptive trajectories and the exploration of the phenotypic space in artificial selection experiments

#### Thursday November 16
[Benegas, et al., preprint](https://www.biorxiv.org/content/10.1101/2022.08.22.504706v3)
DNA language models are powerful predictors of genome-wide variant effects

#### Thursday November 9
[Liu, et al., preprint](https://www.nature.com/articles/s41467-023-41251-4)
Genomes of cultivated and wild Capsicum species provide insights into pepper domestication and population differentiation

#### Thursday November 2
[Zwaenepoel, et al., preprint](https://www.biorxiv.org/content/10.1101/2023.09.24.559235v1)
Polygenic barriers to gene flow: the role of dominance, haploid selection and heterogeneous genetic architectures

### October
#### Thursday October 26
[Stitzer et al., preprint](https://www.biorxiv.org/content/10.1101/2023.09.18.557618v1)
Transposable element abundance subtly contributes to lower fitness in maize


#### Thursday October 19
[Redmond,, et al., preprint](https://www.biorxiv.org/content/10.1101/2023.09.11.557157v1)
Single-plant-omics reveals the cascade of transcriptional changes during the vegetative-to-reproductive transition


#### Thursday October 12
[Khaipho-Burch, et al., 2023](https://www.nature.com/articles/d41586-023-02895-w?utm_source=Nature+Briefing&utm_campaign=ac0c637986-briefing-dy-20230922&utm_medium=email&utm_term=0_c9dfd39373-ac0c637986-46253114)
Genetic modification can improve crop yields — but stop overselling it


#### Thursday October 5
[ Zeitler, et al., 2023](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1010883)
Purging due to self-fertilization does not prevent accumulation of expansion load

### September


#### Thursday September 21
[Raingeval et al., preprint](https://www.biorxiv.org/content/10.1101/2023.09.06.556499v1.full)
Retrotransposon-driven environmental regulation of FLC leads to adaptive response to herbicide


#### Thursday September 14
[Gu et al., 2023](https://www.nature.com/articles/s41588-023-01495-8)
Structure and function of rice hybrid genomes reveal genetic basis and optimal performance of heterosis

### August
#### Thursday August 24
[Sicard, 2023](https://www.nature.com/articles/ncomms8960)
Divergent sorting of a balanced ancestral polymorphism underlies the establishment of gene-flow barriers in Capsella

### July
#### Thursday July 20
[Xiao, 2023](https://www.pnas.org/doi/10.1073/pnas.2222041120)
Adaptive and maladaptive introgression in grapevine domestication 

#### Thursday July 13
[Kelly, 2023](https://onlinelibrary.wiley.com/doi/full/10.1002/evl3.308)
The genomic scale of fluctuating selection in a natural plant population

#### Thursday July 6
[Tenaillon et al., 2023](https://bsapubs.onlinelibrary.wiley.com/doi/full/10.1002/ajb2.16173?af=R)
Crop domestication as a step toward reproductive isolation

### June
#### Thursday June 22
[Wuest et al., 2023](https://www.nature.com/articles/s41467-023-39130-z)
Single-gene resolution of diversity-driven overyielding in plant genotype mixtures

#### Thursday June 15
[Fuller et al., 2023](https://www.cell.com/current-biology/fulltext/S0960-9822(23)00517-1)
Plant domestication and agricultural ecologies

#### Thursday June 1
[Belluchi et al., 2023](https://www.researchsquare.com/article/rs-2976609/v1)
A pan-genome of 72 Arabidopsis thaliana accessions reveals a conserved genome structure throughout the global species range

### May

#### Thursday May 25
[Belluchi et al., 2023](https://www.nature.com/articles/s41467-023-37332-z)
Selection and adaptive introgression guided the complex evolutionary history of the European common bean

#### Thursday May 4
[Simons et al., preprint](https://www.biorxiv.org/content/10.1101/2022.10.04.509926v1.full)
Simple scaling laws control the genetic architectures of human complex traits


### April

#### Thursday April 27
[Mueller et al., 2023](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0284136)
The taming of the weed: Developmental plasticity facilitated plant domestication

#### Thursday April 20
[He et al., preprint](https://www.biorxiv.org/content/10.1101/2023.01.10.523403v2)
Heritable microbiome variation is correlated with source environment in locally adapted maize varieties

### March

#### Thursday March 30
[Zhao et al., 2023](https://www.nature.com/articles/s41477-023-01367-3)
Population genomics unravels the Holocene history of bread wheat and its relatives

#### Thursday March 23
[Soudi et al., preprint](https://www.biorxiv.org/content/10.1101/2023.02.17.528989v1)
Repeatability of adaptation in sunflowers: genomic regions harbouring inversions also drive adaptation in species lacking an inversion

#### Thursday March 16
[Zhong et al., 2022](https://onlinelibrary.wiley.com/doi/10.1111/mec.16454)
Hard versus soft selective sweeps during domestication and improvement in soybean

[Jensen et al., 2023](https://www.nature.com/articles/s41437-022-00575-5)
Population genetic concerns related to the interpretation of empirical outliers and the neglect of common evolutionary processes

[Zhong et al., 2023](https://www.nature.com/articles/s41437-023-00605-w)
Wild progenitors provide a sound baseline model for evolutionary analysis of domesticated crop species

### February

#### Thursday February 23
[Liang et al., 2023](https://www.science.org/doi/10.1126/science.adf1323)
Taxon-specific, phased siRNAs underlie a speciation locus in monkeyflowers

#### Thursday February 9
[Quagliariello et al., 2023](https://www.nature.com/articles/s41467-022-34416-0)
Ancient oral microbiomes support gradual Neolithic dietary shifts towards agriculture

#### Thursday February 2
[Shang et al., preprint](https://www.biorxiv.org/content/10.1101/2021.08.26.457771v5.full)
Drivers of genomic landscapes of differentiation across Populus divergence gradient



### January

#### Thursday January 26
[James , et al 2022](https://www.annualreviews.org/doi/10.1146/annurev-arplant-071221-090809)
Replicated Evolution in Plants

#### Thursday January 19
[Opedal , et al 2022](https://www.pnas.org/doi/10.1073/pnas.2203228120)
Evolvability and trait function predict phenotypic divergence of plant populations

#### Thursday January 12
[Luo , et al 2022](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1010513)
Domestication and selection footprints in Persian walnuts (Juglans regia)



## 2022

### November
#### Thursday November 24
[Díaz-Valenzuela, et al preprint](https://www.biorxiv.org/content/10.1101/2022.10.13.511672v1)
The role of non-additive gene action on gene expression variation in plant domestication

#### Thursday November 17
[Pucker, et al preprint](https://www.biorxiv.org/content/10.1101/2022.10.19.512958v1.full)
Evolutionary blocks to anthocyanin accumulation and the loss of an anthocyanin carrier protein in betalain-pigmented Caryophyllales

### October


#### Thursday October 13
[Muleta, et al 2022](https://www.science.org/doi/10.1126/sciadv.abj4633)
The recent evolutionary rescue of a staple crop depended on over half a century of global germplasm exchange


#### Thursday October 6
[Exposito-Alonso, et al 2022](https://www.science.org/doi/10.1126/science.abn5642)
Genetic diversity loss in the Anthropocene


### September

#### Thursday September 29
[Lopez-Valdivia, et al 2022](https://www.pnas.org/doi/abs/10.1073/pnas.2110245119)
Gradual domestication of root traits in the earliest maize from Tehuacán

#### Thursday September 22
[Todd, et al 2022](https://www.science.org/doi/10.1126/science.abo3503)
The genomic history and global expansion of domestic donkeys

#### Thursday September 15
[Vourlaki, et al preprint](https://www.biorxiv.org/content/10.1101/2022.08.24.505198v1)
Detection of Domestication Signals through the Analysis of the Full Distribution of Fitness Effects using Forward Simulations and Polygenic Adaptation

#### Thursday September 8
[Buckley, et al 2022](https://bmcecolevol.biomedcentral.com/articles/10.1186/s12862-022-01990-2)
Variation in intraspecific demography drives localised concordance but species-wide discordance in response to past climatic change

#### Thursday September 1
[Bieker, et al 2022](https://www.science.org/doi/10.1126/sciadv.abo5115)
Uncovering the genomic basis of an extraordinary plant invasion

### August

#### Thursday August 25
[Lian, et al 2022](https://www.nature.com/articles/s41467-022-31509-8)
The megabase-scale crossover landscape is largely independent of sequence divergence

### July

#### Thursday July 28
[Hu, et al preprint](https://www.biorxiv.org/content/10.1101/2022.07.15.500250v1)
Allele-specific expression reveals multiple paths to highland adaptation in maize

### June

#### Thursday June 23
[Liao, et al 2022](https://www.nature.com/articles/s41467-022-31112-x)
The 3D architecture of the pepper genome and its relationship to function and evolution

#### Thursday June 9
[Fu, et al 2022](https://www.nature.com/articles/s41559-022-01754-7)
Genome-wide analyses of introgression between two sympatric Asian oak species

#### Thursday June 2
[Kivikoski, et al preprint](https://www.biorxiv.org/content/10.1101/2022.05.26.493536v1)
Low heritability of crossover rate in wild sticklebacks

### May


#### Thursday May 12
No C.R.O.P

#### Thursday May 5
[Fulgione, et al 2022](https://www.nature.com/articles/s41467-022-28800-z)
Parallel reduction in flowering time from de novo mutations enable evolutionary rescue in colonizing lineages



### April

#### Thursday April 28
[Li, et al 2022](https://nph.onlinelibrary.wiley.com/doi/10.1111/nph.18026)
CsMYB1 integrates the regulation of trichome development and catechins biosynthesis in tea plant domestication

#### Thursday April 21
[Liu, et al 2022](https://academic.oup.com/mbe/advance-article/doi/10.1093/molbev/msac078/6564429)
A transposon insertion drove the loss of natural seed shattering during foxtail millet domestication

#### Thursday April 14 
Manuscript in progress (contact Markus for access)

#### Thursday April 7
[Solares, et al preprint](https://www.biorxiv.org/content/10.1101/2022.03.30.486474v1)
Insights into the domestication of avocado and potential genetic contributors to heterodichogamy

### March

#### Thursday March 17
[Wohns, et al 2022](https://www.science.org/doi/10.1126/science.abi8264)
A unified genealogy of modern and ancient genomes

#### Thursday March 10
no C.R.O.P

#### Thursday March 3
[Kreiner, et al preprint](https://www.biorxiv.org/content/10.1101/2022.02.25.482047v1)
Rapid adaptation and range expansion in response to agriculture over the last two centuries

### February

#### Thursday February 17
[Battlay, et al 2021](https://doi.org/10.1101/2021.09.13.459985)
Pleiotropy drives repeatability in the genetic basis of adaptation

#### Thursday February 10
[Novo, et al 2022](https://doi.org/10.1371/journal.pgen.1009764)
The estimates of effective population size based on linkage disequilibrium are virtually unaffected by natural selection

#### Thursday February 3
[Monroe, et al 2022](https://www.nature.com/articles/s41586-021-04269-6)
Mutation bias reflects natural selection in Arabidopsis thaliana

### January

#### Thursday January 27
[Dahan-Meir, et al preprint](https://www.biorxiv.org/content/10.1101/2022.01.10.475641v1)
The genetic structure of a wild wheat population has remained associated with microhabitats over 36 years

#### Thursday January 13
[Cai et al 2021](https://www.nature.com/articles/s41467-021-27432-z)
Genomic analyses provide insights into spinach domestication and the genetic basis of agronomic traits

## 2021

### December
#### Thursday December 9
[Monnahan, et al, 2021](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1008945)
Predicting evolutionary change at the DNA level in a natural Mimulus population

#### Thursday December 2
[Gibson, et al, 2021](https://elifesciences.org/articles/64165)
Introgression shapes fruit color convergence in invasive Galápagos tomato


### November

#### Thursday November 25
[Wrightsman, et al, preprint](https://www.biorxiv.org/content/10.1101/2021.11.11.468292v1.full)
Modeling chromatin state from sequence across angiosperms using recurrent convolutional neural networks

#### Thursday November 18
[Naish, et al, 2021](https://www.science.org/doi/10.1126/science.abi7489)
The genetic and epigenetic landscape of the Arabidopsis centromeres

#### Thursday November 4
[Ye, et al, 2021](https://www.nature.com/articles/s41559-019-0976-1)
Genomic evidence of human selection on Vavilovian mimicry


### October

#### Thursday October 28
[Grover, et al, preprint](https://www.biorxiv.org/content/10.1101/2021.10.20.465142v1)
Dual domestication, diversity, and differential introgression in Old World cotton diploids

#### Thursday October 21
[Fuentes et al, 2021](https://doi.org/10.1093/molbev/msab287)
Domestication shapes recombination patterns in tomato

#### Thursday October 7
[Tittes et al, preprint](https://www.biorxiv.org/content/10.1101/2021.09.09.459637v1.full)
Not so local: the population genetics of convergent adaptation in maize and teosinte


### September

#### Thursday September 30
[Morales-Cruz et al, 2021](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02467-z)
Introgression among North American wild grapes (Vitis) fuels biotic and abiotic adaptation

#### Thursday September 9
[Hämälä et al, 2021](https://doi.org/10.1073/pnas.2102914118)
Genomic structural variants constrain and facilitate adaptation in natural populations of Theobroma cacao, the chocolate tree

#### Thursday September 2
[Schaefer et al, 2021](https://www.science.org/doi/10.1126/sciadv.abc0776)
An ancestral recombination graph of human, Neanderthal, and Denisovan genomes

### August

#### Thursday August 26
[ Aguirre-Liguori et al, 2021](https://www.nature.com/articles/s41559-021-01526-9)
The evolutionary genomics of species’ responses to climate change

#### Thursday August 19
[Sachdeva et al, preprint](https://www.biorxiv.org/content/10.1101/2021.08.05.455207v1)
Genetic load and extinction in peripheral populations: the roles of migration, drift and demographic stochasticity

#### Thursday August 12
[Katz et al., 2021](https://elifesciences.org/articles/67784)
Genetic variation, environment and demography intersect to shape Arabidopsis defense metabolite variation across Europe

#### Thursday August 5
[Milla and Osborne, 2021](https://www.nature.com/articles/s41477-021-00905-1)
Crop origins explain variation in global agricultural relevance

### July

#### Thursday July 29
[Todesco et al, preprint](https://www.biorxiv.org/content/10.1101/2021.06.26.449999v1)
Genetic basis and dual adaptive role of floral pigmentation in sunflowers


#### Thursday July 22
[Szukala et al, preprint](https://www.biorxiv.org/content/10.1101/2021.07.05.451094v2)
Polygenic routes lead to parallel altitudinal adaptation in Heliosperma pusillum (Caryophyllaceae)

### May

#### Thursday May 27
[ Ma et al 2021](https://onlinelibrary.wiley.com/doi/pdfdirect/10.1111/tpj.15298)
A chromosome-level Amaranthu cruentus genome assembly highlights gene family evolution and
biosynthetic gene clusters that may underpin the nutritional value of this traditional crop


#### Thursday May 20
[Groen et al preprint](https://doi.org/10.1101/2021.03.16.435597)
Fitness costs and benefits of gene expression plasticity in rice under drought



#### Thursday May 6
[Berdan et al 2021](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1009411)
Deleterious mutation accumulation and the long-term fate of chromosomal inversions

### April

#### Thursday April 29
[Chen et al preprint](https://www.biorxiv.org/content/10.1101/2021.04.07.438828v1)
Portrait of a genus: the genetic diversity of Zea

#### Thursday April 15
[Mabry et al preprint](https://www.biorxiv.org/content/10.1101/2021.04.06.438638v1)
The Evolutionary History of Wild, Domesticated, and Feral Brassica oleracea (Brassicaceae)

#### Thursday April 8
[Burban et al preprint](https://www.biorxiv.org/content/10.1101/2021.03.19.436202v1)
Gene network simulations provide testable predictions for the molecular domestication syndrome

### March

#### Thursday March 25
[Zhong et al 2021](https://www.pnas.org/content/118/5/e2023347118)
DNA methylation-linked chromatin accessibility affects genomic architecture in Arabidopsis

#### Thursday March 18
[Huang et al 2020](https://www.nature.com/articles/s41467-020-19131-y)
Genotype by environment interaction for gene expression in Drosophila melanogaster



#### Thursday March 11
MGM2021


#### Thursday March 4
[Meyer et al 2012](https://nph.onlinelibrary.wiley.com/doi/10.1111/j.1469-8137.2012.04253.x)
Patterns and processes in crop domestication: an historical review and quantitative analysis of 203 global food crops

### February

#### Thursday Febraury 25
[Crouse et al 2020](https://www.genetics.org/content/216/4/957)
Inferring the Allelic Series at QTL in Multiparental Populations

#### Thursday Febraury 18
[Lovell et al 2021](https://www.nature.com/articles/s41586-020-03127-1)
Genomic mechanisms of climate adaptation in polyploid bioenergy switchgrass

#### Thursday Febraury 11
[Liu et al 2021](https://www.nature.com/articles/s41586-020-03091-w)
Genomic basis of geographical adaptation to soil nitrogen in rice

#### Thursday Febraury 4
[Shirsekar et al preprint](https://www.biorxiv.org/content/10.1101/2021.01.22.427575v1)
Fine-scale Population Structure of North American Arabidopsis thaliana Reveals Multiple Sources of Introduction from Across Eurasia

### January

#### Thursday January 28
[Migicovsky et al 2021](https://www.nature.com/articles/s41438-020-00441-7)
Genomic consequences of apple improvement


#### Thursday January 21
[Desbiez-Piat et al preprint](https://www.biorxiv.org/content/10.1101/2020.12.22.423930v1)
Interplay between high-drift and high-selection limits the genetic load in small selfing maize populations

#### Thursday January 14
[Kistler et al 2020](https://www.pnas.org/content/117/52/33124)
Archaeological Central American maize genomes suggest ancient gene flow from South America

## 2020

### December

#### Thursday December 10
[Pérez-Escobar et al, preprint](https://www.biorxiv.org/content/10.1101/2020.11.26.400408v1.full)
Archaeogenomics of a ~2,100-year-old Egyptian leaf provides a new timestamp on date palm domestication

#### Thursday December 3
[James et al, preprint](https://www.biorxiv.org/content/10.1101/2020.02.05.936450v2)
A framework to quantify phenotypic and genotypic parallel evolution


### November

#### Thursday November 26
[Mooney et al, preprint](https://www.biorxiv.org/content/10.1101/2020.11.16.385443v1)
The impact of identity-by-descent on fitness and disease in natural and domesticated Canid populations


#### Thursday November 19
[Zhang et al, preprint](https://www.biorxiv.org/content/10.1101/2020.11.09.374413v1.full)
Evolution of the genetic architecture of local adaptations under genetic rescue is determined by mutational load and polygenicity


#### Thursday November 12
[Mayer et al, 2020](https://www.nature.com/articles/s41467-020-18683-3)
Discovery of beneficial haplotypes for complex traits in maize landraces

#### Thursday November 5
[Tusso et al, preprint](https://www.biorxiv.org/content/10.1101/2020.11.02.364695v1)
Experimental evolution of adaptive divergence under varying degrees of gene flow


### October

#### Thursday October 29
[Zhou et al 2020](https://www.nature.com/articles/s41588-020-00722-w)
Triticum population sequencing provides insights into wheat adaptation

#### Thursday October 22
No meeting!  
[Barton and Keightley 2002](https://www.nature.com/articles/nrg700)
Understanding quantitative genetic variation

#### Thursday October 15
No meeting!  
[Purugganan 2019](https://www.sciencedirect.com/science/article/pii/S0960982219306232#:~:text=Domestication%20is%20a%20co%2Devolutionary,are%20critical%20for%20human%20survival.)
Evolutionary Insights into the Nature of Plant Domestication

#### Thursday October 8
[Kreiner et al preprint](https://www.biorxiv.org/content/10.1101/2020.08.19.257972v1)
The genetic architecture and genomic context of glyphosate resistance

#### Thursday October 1
[Le Corre et al. 2020](https://www.pnas.org/content/early/2020/09/25/2006633117)
Adaptive introgression from maize has facilitated the establishment of teosinte as a noxious weed in Europe

### September

#### Thursday September 24
[Vianna et al. 2020](https://www.pnas.org/content/117/36/22303)
Genome-wide analyses reveal drivers of penguin diversification

  
#### Thursday September 17
[Alonge et al. 2020](https://www.sciencedirect.com/science/article/abs/pii/S0092867420306164)
Major Impacts of Widespread Structural Variation on Gene Expression and Crop Improvement in Tomato

#### Thursday September 10
[Muyle, preprint](https://www.biorxiv.org/content/10.1101/2020.09.04.283333v1)
Investigation Gene body methylation is under selection in Arabidopsis thaliana


#### Thursday September 3
[Dreissig et al 2020](https://nph.onlinelibrary.wiley.com/doi/full/10.1111/nph.16810)
Natural variation in meiotic recombination rate shapes introgression patterns in intraspecific hybrids between wild and domesticated barley


### July

#### Thursday July 16
[Zhang et al 2020](https://www.genetics.org/content/215/3/799)
The Impact of Recessive Deleterious Variation on Signals of Adaptive Introgression in Human Populations

#### Thursday July 9
[Choi and Purugganan preprint](https://www.biorxiv.org/content/10.1101/2020.07.04.188102v1)
Telomere lengths in plants are correlated with flowering time variation

#### Thursday July 2
[Razifrad et al 2020](https://academic.oup.com/mbe/article/37/4/1118/5679792#201242622)
Genomic Evidence for Complex Domestication History of the Cultivated Tomato in Latin America

### June

#### Thursday June 18
[Leder et al 2014](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4327155/)
The Evolution and Adaptive Potential of Transcriptional Variation in Sticklebacks—Signatures of Selection and Widespread Heritability


#### Thursday June 4
[Voichek and Weigel 2020](https://www.nature.com/articles/s41588-020-0612-7)
Identifying genetic variants underlying phenotypic variation in plants without complete genomes


### May

#### Thursday May 28
[Gutaker et al. 2020](https://www.nature.com/articles/s41477-020-0659-6)
Genomic history and ecology of the geographic spread of rice

#### Thursday May 21
Holiday

#### Thursday May 14
[Molin et al. 2020](http://www.plantcell.org/content/early/2020/04/23/tpc.20.00099)
The eccDNA Replicon: A Heritable, Extra-Nuclear Vehicle that Enables Gene Amplification and Glyphosate Resistance in Amaranthus palmeri

#### Thursday May 7

[Mathieson and Scally 2020](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1008624)
What is ancestry?

### March

#### Thursday March 19
No C.R.O.P.


#### Thursday March 12
[Vasseur et al. 2020](https://journals.plos.org/plosbiology/article/file?type=printable&id=10.1371/journal.pbio.3000214)
Nonlinear phenotypic variation uncovers the emergence of heterosis in Arabidopsis thaliana

#### Thursday March 5
[Price et al. 2020](https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.6002)
In the presence of population structure: From genomics to candidate genes underlying local adaptation


### February

#### Thursday February 27
[Groen et al. 2020](https://www.nature.com/articles/s41586-020-1997-2)
The strength and pattern of natural selection on gene expression in rice

#### Thursday February 20
No C.R.O.P - Carnaval 

#### Thursday February 12
[Albers and McVean 2020](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3000586)
Dating genomic variants and shared ancestry in population-scale sequencing data

#### Thursday February 6
[Baduel et al. 2019](https://www.nature.com/articles/s41467-019-13730-0)
Relaxed purifying selection in autopolyploids drives transposable element over-accumulation which provides variants for local adaptation

### January

#### Thursday January 30
[Gilbert et al. 2020](https://www.sciencedirect.com/science/article/abs/pii/S0960982219315659)
Transition from Background Selection to Associative Overdominance Promotes Diversity in Regions of Low Recombination

## 2019

### December

#### Thursday December 12
[Dreissig et al. 2019](https://academic.oup.com/mbe/article/36/9/2029/5519773)
Variation in Recombination Rate Is Shaped by Domestication and Environmental Conditions in Barley

#### Thursday December 5
No C.R.O.P

### November

#### Thursday November 28
No C.R.O.P


#### Thursday November 21
[Lu et al 2019](https://www.nature.com/articles/s41477-019-0548-z)
The prevalence, evolution and chromatin signatures of plant regulatory elements

#### Thursday November 14
[Ostevik et al preprint](https://www.biorxiv.org/content/10.1101/767970v2.full)
Asymmetric gene flow causes cascading reproductive isolation


#### Thursday November 7
[Wisser et al 2019](https://www.genetics.org/content/early/2019/10/15/genetics.119.302780)
The Genomic Basis for Short-Term Evolution of Environmental Adaptation in Maize


### October

#### Thursday October 31
[Grossen et al preprint](https://www.biorxiv.org/content/10.1101/605147v1.full)
Accumulation and purging of deleterious mutations through severe bottlenecks in ibex


#### Thursday October 24
[Samuk et al preprint](https://www.biorxiv.org/content/10.1101/787382v1)
Natural selection shapes variation in genome-wide recombination rate in Drosophila pseudoobscura

#### Thursday October 17
[Rojas-Barrera et al 2019](https://www.pnas.org/content/early/2019/09/26/1817664116)
Contemporary evolution of maize landraces and their wild relatives influenced by gene flow with modern maize varieties

#### Thursday October 10
[Todesco et al preprint](https://www.biorxiv.org/content/10.1101/790279v1)
Massive haplotypes underlie ecotypic differentiation in sunflowers

#### Thursday October 3
Holiday - No C.R.O.P

### September

#### Thursday September 26
No C.R.O.P

#### Thursday September 19
No C.R.O.P

#### Thursday September 12
[Exposito-Alonso et al 2019](https://www.nature.com/articles/s41586-019-1520-9)
Natural selection on the Arabidopsis thaliana genome in present and future climates


#### Thursday September 5
[Mattila et al 2019](https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.5463)
Impact of demography on linked selection in two outcrossing Brassicaceae species

### August


#### Thursday August 29
[Yang et al 2019](https://www.pnas.org/content/116/12/5643.short)
The genetic architecture of teosinte catalyzed and constrained maize domestication


#### Thursday August 22
[Christodoulaki et al preprint](https://www.biorxiv.org/content/10.1101/721340v1.full)
Distance to trait optimum is a crucial factor determining the genomic signature of polygenic adaptation


#### Thursday August 15
[Rougemont et al preprint](https://www.biorxiv.org/content/10.1101/732750v2)
Demographic history, linked selection, and recombination shape the genomic landscape of a broadly distributed Pacific salmon.

#### Thursday August 8
[Therkildsen et al 2019](https://science.sciencemag.org/content/365/6452/487)
Contrasting genomic shifts underlie parallel phenotypic evolution in response to fishing

#### Thursday August 1
[Apuli et al preprint](https://www.biorxiv.org/content/biorxiv/early/2019/06/10/664037.full.pdf)
Constructing a high-density linkage map to infer the genomic landscape of recombination rate variation in European Aspen (Populus tremula) 

### July

#### Thursday July 25
[Hermisson and Pennings 2017](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12808) 
Soft sweeps and beyond: understanding the patterns and probabilities of selection footprints under rapid adaptation

#### Thursday July 18
[Gutaker et al 2019](https://www.nature.com/articles/s41559-019-0921-3.epdf?author_access_token=kznXiIAdgFg9lxODJs8hxtRgN0jAjWel9jnR3ZoTv0Ml7gUsC8aCYaDCupeTf4iBjACiGZ4_78WkjD4m9xJXsdGGTXJSAQ9cibBuRA_HJFVyBfxjb1E2BKNDKL2RXRa9mybyBy508AFZNrq0EuAWzQ%3D%3D) 
The origins and adaptation of European potatoes reconstructed from historical genomes

#### Thursday July 11
[Moest et al preprint](https://www.biorxiv.org/content/10.1101/685685v1) 
Classic and introgressed selective sweeps shape mimicry loci across a butterfly adaptive radiation 

#### Thursday July 4
[Marin et al preprint](https://www.biorxiv.org/content/biorxiv/early/2018/08/06/385377.full.pdf) Evolutionary inference from QST-FST comparisons: disentangling local
adaptation from altitudinal gradient selection in snapdragon plants

### June 
#### Thursday June 27
[Oziolor et al 2019](https://science.sciencemag.org/content/364/6439/455) Adaptive introgression enables evolutionary rescue from extreme environmental pollution

#### Thursday June 20
Holiday

#### Thursday June 13
[Marand et al 2019](http://www.plantcell.org/content/plantcell/early/2019/01/31/tpc.18.00750.full.pdf) Historical Meiotic Crossover Hotspots Fueled Patterns of Evolutionary Divergence in Rice

#### Thursday June 6
[ Stankowski et al preprint](https://www.biorxiv.org/content/10.1101/342352v3) Widespread selection and gene flow shape the genomic landscape during a radiation of monkeyflowers

### May

We took a little break to set up the lab and find a place

### April 


#### Thursday April 18
[Roessler et al preprint](https://www.biorxiv.org/content/10.1101/594812v1) The Genomics of Selfing in Maize (Zea mays ssp. mays): Catching Purging in the Act

#### Thursday April 4
[Xue et al preprint](https://www.biorxiv.org/content/10.1101/588715v1) Hybrid decay: a transgenerational epigenetic decline in vigor and viability triggered in backcross populations of teosinte with maize

### March 

#### Thursday March 28
[Athanasiadis et al preprint](https://www.biorxiv.org/content/10.1101/581389v1) Estimating narrow-sense heritability from genome-wide data in admixed populations

#### Thursday March 21
[Marand et al 2019](http://www.genetics.org/content/early/2019/03/18/genetics.119.302036) Residual Heterozygosity and Epistatic Interactions Underlie the Complex Genetic Architecture of Yield in Diploid Potato

#### Thursday March 14
Break

#### Thursday March 7
[Buffalo and Coop preprint](https://www.biorxiv.org/content/10.1101/559419v1) The Linked Selection Signature of Rapid Adaptation in Temporal Genomic Data

### February 
#### Thursday February 28
[Mackintosh, et al preprint](https://www.biorxiv.org/content/10.1101/534123v1) The determinants of genetic diversity in butterflies - Lewontin's paradox revisited

#### Thursday February 21
[ Haenel, et al 2018](https://onlinelibrary.wiley.com/doi/full/10.1111/mec.14699) Meta‐analysis of chromosome‐scale crossover rate variation in eukaryotes and its significance to evolutionary genomics

#### Thursday February 14
[Yeaman, et al 2018](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1007717) Quantifying how constraints limit the diversity of viable routes to adaptation

#### Thursday February 7
[Chen, et al 2019](https://www.pnas.org/content/116/6/2158) Allele frequency dynamics in a pedigreed natural population

### January 
#### Thursday January 31
[Albert, et al 2019](https://www.pnas.org/content/116/5/1679) Whole-chromosome paints in maize reveal rearrangements, nuclear domains, and chromosomal relationships

#### Thursday January 24
[Ashander, et al preprint](https://www.biorxiv.org/content/early/2018/06/23/354530) Demographic inference in a spatially-explicit ecological model from genomic data: a proof of concept for the Mojave Desert Tortoise

#### Thursday January 17
[Chen, et al 2018](https://www.pnas.org/content/early/2018/12/28/1813852116) Allele frequency dynamics in a pedigreed natural population

#### Thursday January 10
[Schwarzkopf, et al preprint](https://www.biorxiv.org/content/early/2018/11/29/482299) Genetic differentiation and intrinsic genomic features explain variation in recombination hotspots among cocoa tree populations

#### Thursday January 3
[Kistler et al 2018](http://science.sciencemag.org/content/362/6420/1309) Multiproxy evidence highlights a complex evolutionary legacy of maize in South America

## 2018
### December 
#### Thursday December 27
[Kreiner et al preprint](https://www.biorxiv.org/content/early/2018/12/17/498519) Multiple modes of convergent adaptation in the spread of glyphosate-resistant Amaranthus tuberculatus

#### Thursday December 20
[Shah et al preprint](https://www.biorxiv.org/content/biorxiv/early/2018/12/04/485789.full.pdf) Extreme genetic signatures of local adaptation during plant colonization

#### Thursday December 13
[Weng et al 2018](http://www.genetics.org/content/early/2018/12/04/genetics.118.301721) Fine-Grained Analysis of Spontaneous Mutation Spectrum and Frequency in Arabidopsis thaliana

#### Thursday December 6
[Mieulet et al. 2018](https://www.nature.com/articles/s41477-018-0311-x.epdf?author_access_token=xkzOA83JbiSoU_JcVl-jntRgN0jAjWel9jnR3ZoTv0Ns64ESdcFnXqL2H6X2hOFO74BnjG-JklRF4Wbzm1M5_mixFqX7kt5fUEIyqVSE6l8VRhsCCo5jwGw3gxKZ-XSg4c4mto3kDdAQVTl0uW8nBA%3D%3D) Unleashing meiotic crossovers in crops

### November 

#### Thursday November 29
[Kelleher et al preprint](https://www.biorxiv.org/content/early/2018/11/01/458067) Inferring the ancestry of everyone


<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-96594188-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-96594188-4');
</script>
